### ISSUE TITLE
cannot add osu music to queue

### ISSUE THREAD

**Issue by Hoto-Cocoa** [DasWolke/rem-v2#45]
```qa
Found Connection!
Shard:0 BLOCKED FOR 37ms
info:        errno=-2, code=ENOENT, syscall=access, path=audio/481371.mp3, worker=1
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0x4f44213c
    at /root/rem-v2/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
i said it to discord, but I think it would be nice to report the issue to GitHub. so i removed pm and submited new issue.

**Comment by DasWolke** [comment]
ahh, I know what causes this.. Create a folder called audio

**Comment by Hoto-Cocoa** [comment]
```root@DO2:~/rem-v2# mkdir -m 777 audio
mkdir: cannot create directory ‘audio’: File exists
root@DO2:~/rem-v2# ls
audio     config  index.js  locales  node_modules  README.md  structures
commands  DB      LICENSE   modules  package.json  shard.js   temp
root@DO2:~/rem-v2# chmod -R 777 audio
root@DO2:~/rem-v2# ls
audio     config  index.js  locales  node_modules  README.md  structures
commands  DB      LICENSE   modules  package.json  shard.js   temp
root@DO2:~/rem-v2# nodejs index.js
2017-01-10T19:14:29.565Z - info: Spawned Shards!
info:    string worker=1
info:     autoreconnect=true, compress=true, messageLimit=200, disableEveryone=true, getAllUsers=true, firstShardID=0, lastShardID=0, maxShards=1, disableEvents=[typingStart, typingStop, guildMemberSpeaking, messageUpdate], worker=1
info:    Worker started 0/1 worker=1
Shard:0 BLOCKED FOR 549ms
info:       loaded mods worker=1
info:       commands are ready! worker=1
Shard:0 BLOCKED FOR 73ms
voice
Shard:0 BLOCKED FOR 136ms
Shard:0 BLOCKED FOR 129ms
Shard:0 BLOCKED FOR 32ms
qa
Found Connection!
Shard:0 BLOCKED FOR 47ms
info:        errno=-2, code=ENOENT, syscall=access, path=audio/481371.mp3, worker=1
Shard:0 BLOCKED FOR 16ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0x4f44213c
    at /root/rem-v2/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
Already exist, So i changed permissions and get same error.

**Comment by DasWolke** [comment]
Alright. let me see.

**Comment by DasWolke** [comment]
Closed as issue was from missing config data
